### ISSUE TITLE
Error saving generated HID file

### ISSUE THREAD

**Issue by carldanley** [lukekarrys/hid-mapper#1]
I installed `npm` via `brew` and installed this package globally. When I goto save the generated HID config, I run into permissions errors where the console runs into problems.

![http://f.cl.ly/items/2j2p0333042O00063y2y/Image%202014-06-02%20at%208.28.33%20PM.png](http://f.cl.ly/items/2j2p0333042O00063y2y/Image%202014-06-02%20at%208.28.33%20PM.png)
1. We need to work from PWD for file generation process (if local directory is entered).
2. We need to resolve the console from hanging on permissions error.

Maybe we can use an `isWriteablePath` function (or something) to determine whether or not we can and catch any errors before they create problems.

**Comment by lukekarrys** [comment]
Thanks @carldanley. I just published `0.0.2` which should alleviate some of these problems.

The initial problem was just because the code was expecting to write to a directory that I never checked in. :grin: 

But you raise a better point that when installed globally, no one would want to save to `__dirname`. So I changed it so that by default it will attempt to write to `process.cwd()`.

I also changed it to use `fs.writeFile` and then in the callback I'm just logging the error and exiting.

**Comment by lukekarrys** [comment]
From what I read in a quick glance, something like `isWritablePath` is difficult to get right when it comes to the numerous operating systems and user types. Maybe a good alternative is just to log the error, exit and write the output to `stdout`?

**Comment by carldanley** [comment]
Awesome stuff! I'll check out 0.0.2 in a second here and confirm that this resolves me issue (it should). On second thought, I agree with you about `isWritablePath` being difficult, better to just log the error so the user can see what's going on. I really like the idea that we can catch it, dump to console and exit.

If there is an error, is there any way we can persist their configuration somehow? I'd hate to map a controller out and then lose that config and have to redo it.

**Comment by carldanley** [comment]
Also - just tried 0.0.2 and my console still hangs: ![http://f.cl.ly/items/0R0i45281v1J3s2j3K0y/Image%202014-06-02%20at%209.18.58%20PM.png](http://f.cl.ly/items/0R0i45281v1J3s2j3K0y/Image%202014-06-02%20at%209.18.58%20PM.png). Do you have this problem at all?

**Comment by lukekarrys** [comment]
That's odd. It doesn't happen for me

![screen shot 2014-06-02 at 6 26 01 pm](https://cloud.githubusercontent.com/assets/542108/3155328/0deb3ea8-eabe-11e3-8082-11e7ba255394.png)

The line right after the `File saved to...` log is `process.exit(0)`. I have no idea why that would hang the console.

**Comment by lukekarrys** [comment]
I also opened #2 for how to persist a mapping if it can't be saved.

**Comment by carldanley** [comment]
Cool - I'll see if I can submit a PR that fixes the problem I'm having.
